window.LESSON_DATA = {
    addition: {
        title: 'Addition',
        subject: 'Math · Chapter 3 · Beginner',
        icon: '➕',
        iconClass: 'addition',
        totalQuestions: 5,
        hint: 'Practice adding single-digit, double-digit, and multi-digit numbers.',
        questions: [
            { text: '2 + 3 = ?', choices: ['4', '5', '6', '7'], correct: 1, difficulty: 'easy', hint: 'Count up from 2 three steps.', explanation: '2 + 3 = 5.' },
            { text: '7 + 1 = ?', choices: ['6', '7', '8', '9'], correct: 2, difficulty: 'easy', hint: 'Add one more to 7.', explanation: '7 + 1 = 8.' },
            { text: '4 + 5 = ?', choices: ['7', '8', '9', '10'], correct: 2, difficulty: 'easy', hint: 'Count on from 4.', explanation: '4 + 5 = 9.' },
            { text: '10 + 6 = ?', choices: ['14', '15', '16', '17'], correct: 2, difficulty: 'easy', hint: 'Add the ones first, then the tens.', explanation: '10 + 6 = 16.' },
            { text: '12 + 8 = ?', choices: ['18', '19', '20', '21'], correct: 2, difficulty: 'medium', hint: 'Think of 12 + 8 as 10 + 10.', explanation: '12 + 8 = 20.' },
            { text: '15 + 7 = ?', choices: ['20', '21', '22', '23'], correct: 2, difficulty: 'medium', hint: 'Add 5 and 7 first, then add 10.', explanation: '15 + 7 = 22.' },
            { text: '24 + 16 = ?', choices: ['34', '36', '38', '40'], correct: 1, difficulty: 'medium', hint: 'Add the tens, then the ones.', explanation: '24 + 16 = 40.' },
            { text: '38 + 25 = ?', choices: ['53', '57', '60', '63'], correct: 1, difficulty: 'medium', hint: 'Line up the tens and ones.', explanation: '38 + 25 = 63.' },
            { text: '47 + 29 = ?', choices: ['66', '72', '76', '80'], correct: 2, difficulty: 'medium', hint: 'Regroup if needed.', explanation: '47 + 29 = 76.' },
            { text: '63 + 48 = ?', choices: ['101', '105', '109', '111'], correct: 2, difficulty: 'hard', hint: 'Add the tens first, then regroup.', explanation: '63 + 48 = 111.' },
            { text: '128 + 49 = ?', choices: ['167', '171', '176', '177'], correct: 2, difficulty: 'hard', hint: 'Add the ones, then the tens.', explanation: '128 + 49 = 177.' },
            { text: '347 + 186 = ?', choices: ['523', '529', '533', '539'], correct: 3, difficulty: 'hard', hint: 'Use column addition.', explanation: '347 + 186 = 533.' },
            { text: '512 + 289 = ?', choices: ['791', '799', '801', '809'], correct: 2, difficulty: 'hard', hint: 'Regroup the tens carefully.', explanation: '512 + 289 = 801.' },
            { text: '1,245 + 879 = ?', choices: ['2,104', '2,114', '2,124', '2,134'], correct: 2, difficulty: 'hard', hint: 'Add the hundreds, then regroup.', explanation: '1245 + 879 = 2124.' },
            { text: '2,406 + 1,589 = ?', choices: ['3,885', '3,895', '3,985', '3,995'], correct: 2, difficulty: 'hard', hint: 'Add from right to left.', explanation: '2406 + 1589 = 3995.' },
            { text: '3,512 + 2,468 = ?', choices: ['5,870', '5,980', '6,080', '6,180'], correct: 2, difficulty: 'hard', hint: 'Check the regrouping in the hundreds place.', explanation: '3512 + 2468 = 5980.' },
            { text: '8 + 8 = ?', choices: ['14', '15', '16', '17'], correct: 2, difficulty: 'easy', hint: 'Double 8.', explanation: '8 + 8 = 16.' },
            { text: '9 + 6 = ?', choices: ['13', '14', '15', '16'], correct: 2, difficulty: 'easy', hint: 'Start at 9 and count 6 more.', explanation: '9 + 6 = 15.' },
            { text: '22 + 19 = ?', choices: ['39', '40', '41', '42'], correct: 2, difficulty: 'medium', hint: 'Think 20 + 20 and adjust.', explanation: '22 + 19 = 41.' },
            { text: '56 + 37 = ?', choices: ['83', '89', '93', '97'], correct: 2, difficulty: 'medium', hint: 'Add the ones, then the tens.', explanation: '56 + 37 = 93.' }
        ]
    },
    subtraction: {
        title: 'Subtraction',
        subject: 'Math · Chapter 4 · Intermediate',
        icon: '➖',
        iconClass: 'subtraction',
        totalQuestions: 5,
        hint: 'Practice subtracting with regrouping and larger numbers.',
        questions: [
            { text: '8 - 3 = ?', choices: ['4', '5', '6', '7'], correct: 1, difficulty: 'easy', hint: 'Count backwards from 8.', explanation: '8 - 3 = 5.' },
            { text: '9 - 4 = ?', choices: ['3', '4', '5', '6'], correct: 2, difficulty: 'easy', hint: 'Take away 4 from 9.', explanation: '9 - 4 = 5.' },
            { text: '10 - 6 = ?', choices: ['2', '3', '4', '5'], correct: 2, difficulty: 'easy', hint: 'Count down from 10.', explanation: '10 - 6 = 4.' },
            { text: '15 - 7 = ?', choices: ['6', '7', '8', '9'], correct: 2, difficulty: 'easy', hint: 'Subtract the ones first.', explanation: '15 - 7 = 8.' },
            { text: '20 - 9 = ?', choices: ['9', '10', '11', '12'], correct: 2, difficulty: 'medium', hint: 'Think of 20 as 2 tens.', explanation: '20 - 9 = 11.' },
            { text: '32 - 8 = ?', choices: ['20', '22', '24', '26'], correct: 2, difficulty: 'medium', hint: 'Take away 8 from 32.', explanation: '32 - 8 = 24.' },
            { text: '45 - 17 = ?', choices: ['24', '26', '28', '30'], correct: 2, difficulty: 'medium', hint: 'Regroup if needed.', explanation: '45 - 17 = 28.' },
            { text: '58 - 29 = ?', choices: ['21', '25', '27', '29'], correct: 2, difficulty: 'medium', hint: 'Subtract 30 and add 1 back.', explanation: '58 - 29 = 29.' },
            { text: '74 - 36 = ?', choices: ['34', '36', '38', '40'], correct: 2, difficulty: 'medium', hint: 'Borrow from the tens place.', explanation: '74 - 36 = 38.' },
            { text: '93 - 47 = ?', choices: ['34', '36', '38', '46'], correct: 2, difficulty: 'hard', hint: 'Use regrouping carefully.', explanation: '93 - 47 = 46.' },
            { text: '125 - 68 = ?', choices: ['47', '53', '57', '61'], correct: 2, difficulty: 'hard', hint: 'Regroup the tens and ones.', explanation: '125 - 68 = 57.' },
            { text: '241 - 159 = ?', choices: ['72', '76', '82', '88'], correct: 2, difficulty: 'hard', hint: 'Borrow from the hundreds place.', explanation: '241 - 159 = 82.' },
            { text: '503 - 278 = ?', choices: ['215', '225', '235', '245'], correct: 2, difficulty: 'hard', hint: 'Regroup twice if needed.', explanation: '503 - 278 = 225.' },
            { text: '1,208 - 647 = ?', choices: ['551', '561', '571', '581'], correct: 2, difficulty: 'hard', hint: 'Line up the digits carefully.', explanation: '1208 - 647 = 561.' },
            { text: '2,410 - 1,386 = ?', choices: ['912', '924', '934', '944'], correct: 2, difficulty: 'hard', hint: 'Borrow from the thousands place.', explanation: '2410 - 1386 = 1024.' },
            { text: '16 - 9 = ?', choices: ['5', '6', '7', '8'], correct: 2, difficulty: 'easy', hint: 'Count down from 16.', explanation: '16 - 9 = 7.' },
            { text: '11 - 5 = ?', choices: ['4', '5', '6', '7'], correct: 2, difficulty: 'easy', hint: 'Take away 5 from 11.', explanation: '11 - 5 = 6.' },
            { text: '34 - 12 = ?', choices: ['18', '20', '22', '24'], correct: 2, difficulty: 'medium', hint: 'Subtract the tens, then the ones.', explanation: '34 - 12 = 22.' },
            { text: '67 - 23 = ?', choices: ['34', '40', '44', '46'], correct: 2, difficulty: 'medium', hint: 'Subtract the tens first.', explanation: '67 - 23 = 44.' },
            { text: '81 - 27 = ?', choices: ['44', '48', '52', '54'], correct: 2, difficulty: 'medium', hint: 'Borrow from the tens place.', explanation: '81 - 27 = 54.' }
        ]
    },
    plant: {
        title: 'Plant Life',
        subject: 'Science · Chapter 2 · Explorer',
        icon: '🌱',
        iconClass: 'plant',
        totalQuestions: 5,
        hint: 'Learn how plants grow, breathe, and use sunlight.',
        questions: [
            { text: 'What do plants need to make their own food?', choices: ['Moonlight', 'Sunlight', 'Sand', 'Snow'], correct: 1, difficulty: 'easy', hint: 'Plants use energy from the sun.', explanation: 'Plants use sunlight to make food through photosynthesis.' },
            { text: 'What part of a plant usually grows underground?', choices: ['Leaf', 'Root', 'Flower', 'Stem'], correct: 1, difficulty: 'easy', hint: 'Roots anchor the plant and absorb water.', explanation: 'Roots grow underground and take in water.' },
            { text: 'Which part of a plant carries water upward?', choices: ['Stem', 'Root', 'Petal', 'Seed'], correct: 0, difficulty: 'easy', hint: 'The stem supports the plant and moves water.', explanation: 'The stem carries water from the roots to the leaves.' },
            { text: 'What do leaves help a plant do?', choices: ['Sleep', 'Make food', 'Digest bones', 'Sing'], correct: 1, difficulty: 'easy', hint: 'Leaves are the plant food factories.', explanation: 'Leaves use sunlight to make food.' },
            { text: 'What is the name of the process plants use to make food?', choices: ['Digestion', 'Photosynthesis', 'Respiration', 'Evaporation'], correct: 1, difficulty: 'medium', hint: 'It begins with the word photo.', explanation: 'Plants use photosynthesis to make food.' },
            { text: 'Why do plants need water?', choices: ['To float', 'To stay alive and grow', 'To make rocks', 'To become animals'], correct: 1, difficulty: 'medium', hint: 'Water helps plants stay healthy.', explanation: 'Water helps plants grow and stay alive.' },
            { text: 'What do plants release during photosynthesis?', choices: ['Oxygen', 'Soil', 'Sugar cubes', 'Ice'], correct: 0, difficulty: 'medium', hint: 'This gas helps animals breathe.', explanation: 'Plants release oxygen during photosynthesis.' },
            { text: 'What is the purpose of a flower?', choices: ['To make seeds', 'To drink water', 'To dig in soil', 'To scare animals'], correct: 0, difficulty: 'medium', hint: 'Flowers help plants reproduce.', explanation: 'Flowers help plants make seeds.' },
            { text: 'What helps a plant stay upright?', choices: ['Stem', 'Root', 'Leaf', 'Petal'], correct: 0, difficulty: 'medium', hint: 'The stem holds the plant up.', explanation: 'The stem helps the plant stay upright.' },
            { text: 'Which part of a plant absorbs minerals from soil?', choices: ['Roots', 'Leaves', 'Flowers', 'Seeds'], correct: 0, difficulty: 'hard', hint: 'Roots take in nutrients from the ground.', explanation: 'Roots absorb minerals and water from soil.' },
            { text: 'What is the main source of energy for plants?', choices: ['Water', 'Sunlight', 'Wind', 'Soil'], correct: 1, difficulty: 'hard', hint: 'This energy powers photosynthesis.', explanation: 'Sunlight is the main energy source for plants.' },
            { text: 'What do seeds grow into?', choices: ['New plants', 'Rocks', 'Clouds', 'Fish'], correct: 0, difficulty: 'hard', hint: 'Seeds begin a new plant life cycle.', explanation: 'Seeds grow into new plants.' },
            { text: 'Which gas do plants take in from the air?', choices: ['Oxygen', 'Carbon dioxide', 'Helium', 'Hydrogen'], correct: 1, difficulty: 'hard', hint: 'Plants use this gas to make food.', explanation: 'Plants take in carbon dioxide for photosynthesis.' },
            { text: 'What do plants need to grow strong?', choices: ['Sunlight, water, and nutrients', 'Only rocks', 'Only shade', 'Only wind'], correct: 0, difficulty: 'hard', hint: 'Plants need several things to thrive.', explanation: 'Plants need sunlight, water, and nutrients to grow.' },
            { text: 'What is the job of pollen?', choices: ['To carry genetic material for reproduction', 'To cool the plant', 'To make roots', 'To create soil'], correct: 0, difficulty: 'hard', hint: 'Pollen helps plants make seeds.', explanation: 'Pollen helps plants reproduce.' },
            { text: 'Which part of the plant is often colorful and attracts pollinators?', choices: ['Flower', 'Root', 'Stem', 'Leaf'], correct: 0, difficulty: 'easy', hint: 'Bright colors help attract bees and butterflies.', explanation: 'Flowers are colorful and attract pollinators.' },
            { text: 'What is a seed?', choices: ['A baby plant inside a protective coat', 'A leaf', 'A root hair', 'A rock'], correct: 0, difficulty: 'easy', hint: 'Seeds begin new plant life.', explanation: 'A seed contains a baby plant and food supply.' },
            { text: 'What do roots hold the plant in place for?', choices: ['To make fruit', 'To keep the plant steady', 'To produce pollen', 'To make a stem'], correct: 1, difficulty: 'medium', hint: 'Roots help prevent the plant from falling over.', explanation: 'Roots anchor the plant in the soil.' },
            { text: 'Which part of the plant is where most photosynthesis happens?', choices: ['Leaf', 'Root', 'Seed', 'Flower'], correct: 0, difficulty: 'medium', hint: 'Leaves have chlorophyll for photosynthesis.', explanation: 'Photosynthesis mainly happens in leaves.' },
            { text: 'What do plants make with sunlight and water?', choices: ['Food', 'Sand', 'Dust', 'Rocks'], correct: 0, difficulty: 'medium', hint: 'This is the plant fuel.', explanation: 'Plants make food using sunlight and water.' }
        ]
    },
    reading: {
        title: 'Story Comprehension',
        subject: 'Reading · Chapter 2 · Story Time',
        icon: '📚',
        iconClass: 'reading',
        totalQuestions: 5,
        hint: 'Practice reading comprehension and story clues.',
        questions: [
            { text: 'What is the main idea of a story?', choices: ['The ending only', 'The most important message', 'The title only', 'The author’s age'], correct: 1, difficulty: 'easy', hint: 'Ask what the story is mostly about.', explanation: 'The main idea is the central message of the story.' },
            { text: 'If a character is brave, what might they do?', choices: ['Hide from every challenge', 'Face a problem with courage', 'Sleep all day', 'Ignore everyone'], correct: 1, difficulty: 'easy', hint: 'Brave characters take action.', explanation: 'Brave characters face challenges courageously.' },
            { text: 'What does a setting tell you?', choices: ['Where and when the story happens', 'How many pages a book has', 'The color of the ink', 'The author’s name'], correct: 0, difficulty: 'easy', hint: 'Think about place and time.', explanation: 'The setting tells where and when the story happens.' },
            { text: 'What is a clue in a story?', choices: ['A hint that helps you understand something', 'A sound the book makes', 'A page number', 'A bookmark'], correct: 0, difficulty: 'easy', hint: 'Clues guide us to meaning.', explanation: 'A clue is a hint that helps readers understand the story.' },
            { text: 'What is a character?', choices: ['A person, animal, or being in a story', 'The title of a book', 'A sentence starter', 'A type of paper'], correct: 0, difficulty: 'medium', hint: 'Characters are the people or beings in the story.', explanation: 'Characters are the people or beings in a story.' },
            { text: 'What is the purpose of a beginning in a story?', choices: ['To introduce the characters and setting', 'To tell you the ending', 'To make the book longer', 'To show the page numbers'], correct: 0, difficulty: 'medium', hint: 'The beginning sets up the story.', explanation: 'The beginning introduces the characters and setting.' },
            { text: 'What does “predict” mean in reading?', choices: ['To guess what may happen next', 'To stop reading', 'To copy the words', 'To count pages'], correct: 0, difficulty: 'medium', hint: 'Prediction is an informed guess.', explanation: 'To predict means to make an educated guess about what happens next.' },
            { text: 'Why might an author use dialogue?', choices: ['To show characters speaking', 'To make the book heavier', 'To hide the plot', 'To remove punctuation'], correct: 0, difficulty: 'medium', hint: 'Dialogue uses speaking lines.', explanation: 'Dialogue shows the characters speaking.' },
            { text: 'What is a summary?', choices: ['A short retelling of the main points', 'A list of page numbers', 'A poem about the story', 'The title of a chapter'], correct: 0, difficulty: 'medium', hint: 'A summary includes the main ideas.', explanation: 'A summary is a short retelling of the important points.' },
            { text: 'What can you infer from a story?', choices: ['You can draw a conclusion from clues', 'You can change the ending', 'You can skip chapters', 'You can erase the characters'], correct: 0, difficulty: 'hard', hint: 'Inference means using clues to understand more.', explanation: 'Inference means drawing a conclusion from the clues in the story.' },
            { text: 'Why do authors include details?', choices: ['To make the story more vivid and clear', 'To confuse the reader', 'To shorten the story', 'To hide the title'], correct: 0, difficulty: 'hard', hint: 'Details help readers picture the events.', explanation: 'Details make a story richer and easier to understand.' },
            { text: 'What does “theme” mean in a story?', choices: ['The main lesson or message', 'The font size', 'The number of pages', 'The chapter heading'], correct: 0, difficulty: 'hard', hint: 'Theme is the big lesson.', explanation: 'The theme is the story’s central lesson or message.' },
            { text: 'What should you do when you find an unfamiliar word?', choices: ['Ignore it', 'Use context clues or ask for help', 'Read it backwards', 'Skip the sentence'], correct: 1, difficulty: 'hard', hint: 'Context clues help you understand new words.', explanation: 'Use context clues or ask for help when a word is unfamiliar.' },
            { text: 'What is the difference between fact and opinion?', choices: ['Facts can be proven; opinions are beliefs', 'Facts are always short; opinions are long', 'Facts are always true; opinions are always false', 'There is no difference'], correct: 0, difficulty: 'hard', hint: 'A fact is something that can be checked.', explanation: 'Facts can be proven, while opinions reflect beliefs or feelings.' },
            { text: 'Why do we reread a passage?', choices: ['To understand it better and catch details', 'To make it longer', 'To change the story', 'To remove the title'], correct: 0, difficulty: 'hard', hint: 'Rereading helps deepen understanding.', explanation: 'Rereading helps us understand details and meaning more clearly.' },
            { text: 'What is a setting detail?', choices: ['A description that shows where or when something happens', 'A page number', 'A spelling mistake', 'A chapter list'], correct: 0, difficulty: 'easy', hint: 'Setting details add context.', explanation: 'Setting details help show where and when events happen.' },
            { text: 'What is the purpose of a conclusion?', choices: ['To wrap up the story and show the outcome', 'To introduce a new problem', 'To hide the ending', 'To change the author'], correct: 0, difficulty: 'easy', hint: 'The ending tells what happened.', explanation: 'The conclusion wraps up the story and shares the outcome.' },
            { text: 'What does “sequence” mean?', choices: ['The order of events', 'The size of a book', 'The color of text', 'The number of words'], correct: 0, difficulty: 'medium', hint: 'Sequence means order.', explanation: 'Sequence is the order of events in a story.' },
            { text: 'How can you tell a character is changing?', choices: ['By noticing their actions and feelings over time', 'By counting the pages', 'By changing the font', 'By skipping the middle'], correct: 0, difficulty: 'medium', hint: 'Character change is revealed over time.', explanation: 'Character change is shown by how their actions and feelings evolve.' },
            { text: 'Why would an author use a metaphor?', choices: ['To make a comparison in a vivid way', 'To remove adjectives', 'To shorten the story', 'To add page numbers'], correct: 0, difficulty: 'medium', hint: 'A metaphor compares without using “like” or “as”.', explanation: 'A metaphor makes a comparison in a vivid, imaginative way.' }
        ]
    },
    ancient: {
        title: 'Ancient Civilizations',
        subject: 'History · Chapter 2 · Intermediate',
        icon: '🏛️',
        iconClass: 'ancient',
        totalQuestions: 5,
        hint: 'Explore ancient rivers, leaders, inventions, and landmarks.',
        questions: [
            { text: 'Which ancient civilization built the pyramids of Giza?', choices: ['Romans', 'Egyptians', 'Greeks', 'Chinese'], correct: 1, difficulty: 'easy', hint: 'They lived along the Nile River.', explanation: 'The Egyptians built the pyramids of Giza.' },
            { text: 'Mesopotamia was located between which two rivers?', choices: ['Nile and Amazon', 'Tigris and Euphrates', 'Yangtze and Yellow', 'Indus and Ganges'], correct: 1, difficulty: 'easy', hint: 'Its name means “land between rivers.”', explanation: 'Mesopotamia sat between the Tigris and Euphrates.' },
            { text: 'Which civilization is known as the birthplace of democracy?', choices: ['Egypt', 'Rome', 'Greece', 'China'], correct: 2, difficulty: 'easy', hint: 'Athens was one of its famous city-states.', explanation: 'Ancient Greece is known as the birthplace of democracy.' },
            { text: 'The Great Wall belongs to which civilization?', choices: ['Roman', 'Chinese', 'Persian', 'Greek'], correct: 1, difficulty: 'easy', hint: 'It was built to defend the empire.', explanation: 'The Great Wall belongs to China.' },
            { text: 'Which writing system was used by Ancient Egypt?', choices: ['Latin', 'Alphabet', 'Hieroglyphics', 'Cuneiform'], correct: 2, difficulty: 'easy', hint: 'Picture symbols carved on temples.', explanation: 'Ancient Egypt used hieroglyphics.' },
            { text: 'What was the main purpose of the Roman roads?', choices: ['To help armies and trade travel', 'To keep fish alive', 'To grow crops', 'To collect rain'], correct: 0, difficulty: 'medium', hint: 'Roads helped movement across the empire.', explanation: 'Roman roads helped armies and trade travel efficiently.' },
            { text: 'What was a common feature of city life in ancient Mesopotamia?', choices: ['Flat rooftops and canals', 'Snowy mountains', 'Desert islands', 'Volcanic lava'], correct: 0, difficulty: 'medium', hint: 'Rivers helped support agriculture.', explanation: 'Mesopotamia used irrigation canals and river systems.' },
            { text: 'What was the name of the famous writing system used in Mesopotamia?', choices: ['Hieroglyphics', 'Cuneiform', 'Latin', 'Braille'], correct: 1, difficulty: 'medium', hint: 'It involved wedge-shaped marks.', explanation: 'Mesopotamians used cuneiform.' },
            { text: 'Which river was important to Ancient Egypt?', choices: ['Amazon River', 'Nile River', 'Yangtze River', 'Mississippi River'], correct: 1, difficulty: 'medium', hint: 'It flooded and made farming possible.', explanation: 'The Nile River was crucial to Egypt.' },
            { text: 'What was the Roman Forum?', choices: ['A marketplace and civic center', 'A palace for kings', 'A mountain pass', 'A giant wall'], correct: 0, difficulty: 'medium', hint: 'It was a central public space.', explanation: 'The Roman Forum was a central marketplace and civic area.' },
            { text: 'Who was Alexander the Great?', choices: ['A Roman emperor', 'A Macedonian conqueror', 'A Chinese ruler', 'An Egyptian pharaoh'], correct: 1, difficulty: 'hard', hint: 'He conquered a huge empire in a short time.', explanation: 'Alexander the Great was a Macedonian conqueror.' },
            { text: 'What was one important achievement of the Ancient Chinese?', choices: ['Inventing paper', 'Building the pyramids', 'Creating the Roman forum', 'Writing in hieroglyphics'], correct: 0, difficulty: 'hard', hint: 'It helped record information more easily.', explanation: 'Ancient Chinese invented paper.' },
            { text: 'What is an aqueduct?', choices: ['A bridge-like structure for carrying water', 'A castle wall', 'A type of chariot', 'A sacred temple'], correct: 0, difficulty: 'hard', hint: 'Romans built these to move water long distances.', explanation: 'Aqueducts carried water over long distances.' },
            { text: 'What made the Nile River so important to Egypt?', choices: ['It provided water and fertile soil', 'It was full of gold', 'It had no fish', 'It flowed only in winter'], correct: 0, difficulty: 'hard', hint: 'The river nourished crops and life.', explanation: 'The Nile helped create fertile farmland.' },
            { text: 'What is a pharaoh?', choices: ['A ruler of Ancient Egypt', 'A Roman soldier', 'A Greek philosopher', 'A Chinese emperor'], correct: 0, difficulty: 'hard', hint: 'They ruled Egypt.', explanation: 'A pharaoh was the ruler of ancient Egypt.' },
            { text: 'What was the purpose of the pyramids?', choices: ['To serve as tombs for rulers', 'To store grain', 'To hold armies', 'To guide ships'], correct: 0, difficulty: 'easy', hint: 'They were built for burial chambers.', explanation: 'The pyramids were tombs for rulers.' },
            { text: 'What did the Greeks value?', choices: ['Democracy and learning', 'Only war and conquest', 'Only farming', 'Only trade'], correct: 0, difficulty: 'easy', hint: 'Greek city-states had public debate.', explanation: 'The Greeks valued democracy and intellectual life.' },
            { text: 'How did the Romans spread their influence?', choices: ['Through roads, armies, and law', 'Through snow and ice', 'Through only fishing', 'Through only music'], correct: 0, difficulty: 'medium', hint: 'Their empire depended on infrastructure and military strength.', explanation: 'The Romans spread influence using roads, armies, and law.' },
            { text: 'What was one major use of the Great Wall?', choices: ['To defend the empire', 'To hold water', 'To capture stars', 'To store books'], correct: 0, difficulty: 'medium', hint: 'It protected against invasions.', explanation: 'The Great Wall protected China from invasions.' },
            { text: 'What was a common feature of ancient civilizations?', choices: ['Developing cities and systems of government', 'Living only underground', 'Using only one language worldwide', 'Avoiding trade'], correct: 0, difficulty: 'medium', hint: 'Civilizations built organized societies.', explanation: 'Ancient civilizations built cities and governments.' }
        ]
    }
};
